id: P007898
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:47:58.520734
source_metadata:
  id: bdr:W00EGS1016759
  title: ཀཾ་ཚང་ཆོས་སྤྱོད་སོགས་ཁ་ཏོན་གཅེས་བཏུས
  author: ''
  volumes:
    b97ee327c25b4d7fbb2f6d8465d61d03:
      image_group_id: I01JW4
      title: ''
      volume_number: 1
      total_pages: 920
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
