id: P007898
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016759
  title: ཀཾ་ཚང་ཆོས་སྤྱོད་སོགས་ཁ་ཏོན་གཅེས་བཏུས
  author: ''
  volumes:
    1578e321c24240e5bb7a4e69018f3ae9:
      image_group_id: I01JW4
      title: ''
      volume_number: 1
      total_pages: 920
ebook_metadata:
  title: ཀཾ་ཚང་ཆོས་སྤྱོད་སོགས་ཁ་ཏོན་གཅེས་བཏུས
  author: ''
  sku: P007898
  cover: cover.jpg
  layers:
  - pagination
